version: "3"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ems1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Kibiego22@
    volumes:
      - ./backend:/ems
    networks:
      - employee-network
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ems1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Kibiego22@
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - employee-network
networks:
  employee-network:
