# Generated by Django 4.2.1 on 2023-06-18 17:00

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('coName', models.CharField(max_length=50, primary_key='true', serialize=False, unique='true')),
                ('coEmail', models.EmailField(max_length=254)),
                ('coLogo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('coAddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('first_name', models.CharField(max_length=50, primary_key='true', serialize=False, unique='true')),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empapp.company')),
            ],
        ),
    ]
