# Generated by Django 4.2.2 on 2023-07-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
