# Generated by Django 4.2.2 on 2023-06-30 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_remove_employee_user_employee_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='training',
            name='employees',
        ),
        migrations.AddField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empapp.employee'),
        ),
        migrations.AddField(
            model_name='training',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empapp.employee'),
        ),
    ]
