# Generated by Django 4.2.2 on 2023-06-30 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_remove_document_employees_remove_training_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empapp.employee'),
        ),
    ]
