# Generated by Django 4.2.1 on 2023-06-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0008_attendance_user_department_user_document_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='bonus',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
