# Generated by Django 4.2.1 on 2023-06-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0009_alter_role_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='deductions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
