# Generated by Django 4.2.1 on 2023-06-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0010_alter_payroll_deductions_alter_payroll_net_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_relationship',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
