# Generated by Django 4.1.5 on 2023-06-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0014_alter_company_coname_alter_department_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='user',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.RemoveField(
            model_name='training',
            name='user',
        ),
    ]
